<div class="container footer">
      <div class="row">
        <div class="column grid_6">
          &copy; 2011 Grace Blue
        </div>

        <div class="column grid_6">
          <ul class="footer_nav">
            <li><a href="#">Page item</a></li>
            <li><a href="#">Page item</a></li>
          </ul>
        </div>
      </div><!-- End row -->
    </div><!-- End footer -->
  </body>
</html>
