<?php

/**
 *
 * ProcessWire Module
 * PageEditCheckState
 *
 * @author Philipp 'Soma' Urlich
 * 
 * @created 2011/09/09
 */

class PageEditCheckState extends WireData implements Module{

	public static function getModuleInfo(){
		return array(
			'title' 	=> 'Page Edit Check State', 
			'version' 	=> 100, 
			'summary' 	=> 'This module adds a confirm dialog before leaving a page if its content has changed. Prevents losing unsaved data by accident. This check is performed on all admin edit forms.',
			'href' 		=> 'http://processwire.com/talk/index.php/topic,473.0.html',
			'singular' 	=> true, 
			'autoload' 	=> true, 
			);
	}
	
	public function init(){
		$requrl = $_SERVER['REQUEST_URI'];
		// when editing a page
		if( strpos($requrl, $this->config->urls->admin . 'page/edit/?id=') ) {
			$this->addHookAfter('Process::execute',$this,'execute');
		}
		// when editing templates, fields, users, roles, permissions, module edit 
		elseif( strpos($requrl, $this->config->urls->admin . 'template/edit?id=')
			|| strpos($requrl, $this->config->urls->admin . 'field/edit?id=')
			|| strpos($requrl, $this->config->urls->admin . 'users/edit/?id=')
			|| strpos($requrl, $this->config->urls->admin . 'roles/edit/?id=')
			|| strpos($requrl, $this->config->urls->admin . 'permissions/edit/?id=')
			|| strpos($requrl, $this->config->urls->admin . 'module/edit?name=')
			){
			$this->addHookAfter('Process::executeEdit',$this,'execute');	
		}
	}
	
	public function execute(HookEvent $event){
		$this->config->scripts->add($this->config->urls->PageEditCheckState . "PageEditCheckState.js");
	}	
}